stages:
  - build
  - unittest
  - test
  - package

before_script:
  - echo "before"
  - pwd
  - tree

after_script:
  - echo "after"
  - pwd
  - tree

###################################
# word_count example microservice
###################################

word_count_compile:
  stage: build
  tags: irods
  script:
    - pwd
    - tree

word_count_unittest:
  stage: unittest
  tags: irods
  script:
    - pwd
    - tree

word_count_test:
  stage: test
  tags: irods
  script:
    - pwd
    - tree

word_count_package:
  stage: package
  tags: irods
  script:
    - pwd
    - tree
