variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - build

###################################
# setup container
###################################
centos7_4_1_11_test:
  stage: test
  tags:
    - irods
  script:
    - pwd
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_COMMIT_TAG
    - ./irods-ci-server/down centos7_4_1_11
    - ./irods-ci-server/up centos7_4_1_11 --vol .
    - docker exec -u $( id -u):$( id -g) centos7_4_1_11_icat_1 make -C /build/
    - docker exec -u $( id -u):$( id -g) centos7_4_1_11_icat_1 make -C /build/ test
    - docker exec centos7_4_1_11_icat_1 make -C /build/ install
    - echo Todo_functional_test
    - ./irods-ci-server/down centos7_4_1_11

centos7_4_1_11_build:
  stage: build
  tags:
    - irods
  script:
    - pwd
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_COMMIT_TAG
    - ./irods-ci-server/down irods-ci-server/centos7_4_1_11
    - ./irods-ci-server/up irods-ci-server/centos7_4_1_11 --vol .
    - ./irods-ci-server/rpm/build_rpm.sh 4_1_11 msi-persistent-id $CI_COMMIT_REF_NAME $CI_COMMIT_TAG
    - cp RPMS/4_1_11/x86_64/*.rpm /repos/CentOS/7/irods-4.1.11/Packages/
    - createrepo --update /repos/CentOS/7/irods-4.1.11
    - ./irods-ci-server/down irods-ci-server/centos7_4_1_11
