variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - setup
  - build
  - test
  - install
  - package
  - shutdown

###################################
# setup container
###################################
centos7_4_1_11_setup:
  stage: setup
  tags:
    - irods
  script:
    - pwd
    - ./irods-ci-server/down centos7_4_1_11
    - ./irods-ci-server/up centos7_4_1_11 --vol .
  
centos7_4_1_11_build:
  stage: build
  tags:
    - irods
  script:
    - docker exec centos7_4_1_11_icat_1 make -C /build/

centos7_4_1_11_test:
  stage: test
  tags:
    - irods
  script:
    - docker exec centos7_4_1_11_icat_1 make -C /build/ test

centos7_4_1_11_install:
  stage: install
  tags:
    - irods
  script:
    - docker exec centos7_4_1_11_icat_1 make -C /build/ install

centos7_4_1_11_package:
  stage: package
  tags:
    - irods
  script:
    - irods-ci-server/rpm/build_rpm.sh 4_1_11 msi-persistent-id

centos7_4_1_11_init:
  stage: shutdown
  tags:
    - irods
  script:
    - pwd
    - ./irods-ci-server/down centos7_4_1_11

