variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - install
  - functional_test
  - package

before_script:
  - pwd
  - ./irods-ci-server/up centos7_4_1_11 --vol .

after_script:
  - pwd
  - ./irods-ci-server/down centos7_4_1_11

###################################
# word_count example microservice
###################################
centos7_4_1_11_build:
  stage: build
  tags:
    - irods
  script:
    - docker exec centos7_4_1_11_icat_1 make -C /build/msi_wordcount

centos7_4_1_11_test:
  stage: test
  tags:
    - irods
  script:
    - docker exec centos7_4_1_11_icat_1 make -C /build/msi_wordcount test

centos7_4_1_11_install:
  stage: install
  tags:
    - irods
  script:
    - docker exec centos7_4_1_11_icat_1 make -C /build/msi_wordcount install

centos7_4_1_11_functional_test:
  stage: functional_test
  tags:
    - irods
  script:
    - docker exec centos7_4_1_11_icat_1 make -C /build/msi_wordcount functional_test

centos7_4_1_11_package:
  stage: package
  tags:
    - irods
  script:
    - docker exec centos7_4_1_11_icat_1 make -C /build/msi_wordcount package

