variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

###################################
# setup container
###################################
centos7_4_1_11_setup:
  stage: test
  tags:
    - irods
  script:
    - pwd
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_COMMIT_TAG
    - ./irods-ci-server/down centos7_4_1_11
    - ./irods-ci-server/up centos7_4_1_11 --vol .
    - docker exec centos7_4_1_11_icat_1 make -C /build/
    - docker exec centos7_4_1_11_icat_1 make -C /build/ test
    - docker exec centos7_4_1_11_icat_1 make -C /build/ install
    - docker exec centos7_4_1_11_icat_1 chown -R $( id -u):$( id -g) /build
    - ./irods-ci-server/down centos7_4_1_11
