variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - setup
  - build
  - test
  - install
  - functional_test
  - package
  - shutdown

###################################
# setup container
###################################
centos7_4_1_11_init:
  stage: init
  tags:
    - irods
  script:
    - pwd
    - ./irods-ci-server/up centos7_4_1_11 --vol
  
centos7_4_1_11_build:
  stage: build
  tags:
    - irods
  script:
    - docker exec centos7_4_1_11_icat_1 make -C /build/msi_wordcount

centos7_4_1_11_test:
  stage: test
  tags:
    - irods
  script:
    - docker exec centos7_4_1_11_icat_1 make -C /build/msi_wordcount test

centos7_4_1_11_install:
  stage: install
  tags:
    - irods
  script:
    - docker exec centos7_4_1_11_icat_1 make -C /build/msi_wordcount install

centos7_4_1_11_functional_test:
  stage: functional_test
  tags:
    - irods
  script:
    - docker exec centos7_4_1_11_icat_1 make -C /build/msi_wordcount functional_test

centos7_4_1_11_package:
  stage: package
  tags:
    - irods
  script:
    - docker exec centos7_4_1_11_icat_1 make -C /build/msi_wordcount package

centos7_4_1_11_init:
  stage: shutdown
  tags:
    - irods
  script:
    - pwd
    - ./irods-ci-server/down centos7_4_1_11

