variables:
  GIT_SUBMODULE_STRATEGY: recursive
  YUM_SERVER: software@software.irodspoc-sara.surf-hosted.nl
  PACKAGE_NAME: msi-persistent-id
stages:
  - test
  - build
  - publish

before_script:
  - rm -f .variables
  - |
      if [ "$CI_REGISTRY" = "git.ia.surfsara.nl:5050" ]
      then
        echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin  $CI_REGISTRY;
        echo "export REGISTRY=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/irods-ci-server" >> .variables
      else
        echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin  $REGISTRY;
        echo "export REGISTRY=$REGISTRY" >> .variables
      fi
  - docker-compose -f build/docker-compose.yml down -v

after_script:
  - docker-compose -f build/docker-compose.yml rm -f
  - docker-compose -f build/docker-compose.yml down -v

# ###############################
# test
# ###############################
centos7_4_1_12_test:
  stage: test
  tags:
    - irods
  variables:
    VERSION: centos7_4_1_12
    VOLUME: ..
    PROJECT: $CI_PROJECT_NAMESPACE
  script:
    - build/gitlab_test.sh

centos7_4_2_6_test:
  stage: test
  tags:
    - irods
  variables:
    VERSION: centos7_4_2_6
    VOLUME: ..
    PROJECT: $CI_PROJECT_NAMESPACE
  script:
    - build/gitlab_test.sh

# ###############################
# iRODS 4.1.x
# ###############################
centos7_4_1_11_build:
  stage: build
  tags:
    - irods
  variables:
    PROJECT: $CI_PROJECT_NAMESPACE
    VERSION: centos7_4_1_11
    VOLUME: ..
  script:
    - build/gitlab_build.sh

centos7_4_1_11_publish:
  stage: publish
  tags:
    - irods
  variables:
    PROJECT: $CI_PROJECT_NAMESPACE
    VERSION: centos7_4_1_11
    VOLUME: ..
  script:
    - build/gitlab_publish.sh

centos7_4_1_12_build:
  stage: build
  tags:
    - irods
  variables:
    PROJECT: $CI_PROJECT_NAMESPACE
    VERSION: centos7_4_1_12
    VOLUME: ..
  script:
    - build/gitlab_build.sh

centos7_4_1_12_publish:
  stage: publish
  tags:
    - irods
  variables:
    PROJECT: $CI_PROJECT_NAMESPACE
    VERSION: centos7_4_1_12
    VOLUME: ..
  script:
    - build/gitlab_publish.sh

# ###############################
# iRODS 4.2.x
# ###############################

# ###
centos7_4_2_3_build:
  stage: build
  tags:
    - irods
  variables:
    PROJECT: $CI_PROJECT_NAMESPACE
    VERSION: centos7_4_2_3
    VOLUME: ..
  script:
    - build/gitlab_build.sh

centos7_4_2_3_publish:
  stage: publish
  tags:
    - irods
  variables:
    PROJECT: $CI_PROJECT_NAMESPACE
    VERSION: centos7_4_2_3
    VOLUME: ..
  script:
    - build/gitlab_publish.sh

# ###
centos7_4_2_4_build:
  stage: build
  tags:
    - irods
  variables:
    PROJECT: $CI_PROJECT_NAMESPACE
    VERSION: centos7_4_2_4
    VOLUME: ..
  script:
    - build/gitlab_build.sh

centos7_4_2_4_publish:
  stage: publish
  tags:
    - irods
  variables:
    PROJECT: $CI_PROJECT_NAMESPACE
    VERSION: centos7_4_2_4
    VOLUME: ..
  script:
    - build/gitlab_publish.sh

# ###
centos7_4_2_5_build:
  stage: build
  tags:
    - irods
  variables:
    PROJECT: $CI_PROJECT_NAMESPACE
    VERSION: centos7_4_2_5
    VOLUME: ..
  script:
    - build/gitlab_build.sh

centos7_4_2_5_publish:
  stage: publish
  tags:
    - irods
  variables:
    PROJECT: $CI_PROJECT_NAMESPACE
    VERSION: centos7_4_2_5
    VOLUME: ..
  script:
    - build/gitlab_publish.sh

# ###
centos7_4_2_6_build:
  stage: build
  tags:
    - irods
  variables:
    PROJECT: $CI_PROJECT_NAMESPACE
    VERSION: centos7_4_2_6
    VOLUME: ..
  script:
    - build/gitlab_build.sh

centos7_4_2_6_publish:
  stage: publish
  tags:
    - irods
  variables:
    PROJECT: $CI_PROJECT_NAMESPACE
    VERSION: centos7_4_2_6
    VOLUME: ..
  script:
    - build/gitlab_publish.sh

# ###
centos7_4_2_7_build:
  stage: build
  tags:
    - irods
  variables:
    PROJECT: $CI_PROJECT_NAMESPACE
    VERSION: centos7_4_2_7
    VOLUME: ..
  script:
    - build/gitlab_build.sh

centos7_4_2_7_publish:
  stage: publish
  tags:
    - irods
  variables:
    PROJECT: $CI_PROJECT_NAMESPACE
    VERSION: centos7_4_2_7
    VOLUME: ..
  script:
    - build/gitlab_publish.sh
